/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "weather_reading.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(WeatherReadingMessage, WeatherReadingMessage, AUTO)







